# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "shopcord"
client_id = "4609cf9a5d4741847fd2c187928b3f17"
application_url = "https://armed-racing-peas-cg.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products, read_orders, write_orders"

[auth]
redirect_urls = [
  "https://armed-racing-peas-cg.trycloudflare.com/auth/callback",
  "https://armed-racing-peas-cg.trycloudflare.com/auth/shopify/callback",
  "https://armed-racing-peas-cg.trycloudflare.com/api/auth/callback",
  "https://armed-racing-peas-cg.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "development-store-12345.myshopify.com"
